declare module '@env' {
    export const API_URL: string
    export const URL_LOGIN: string
    export const URL_REGISTER: string
    export const URL_REFRESH_TOKEN: string
    export const URL_LOGOUT: string
    export const URL_FORGOT_PASSWORD: string
    export const URL_GET_WORKOUT_HISTORY: string
    export const URL_GET_ERRORS_OF_WORKOUT_BY_ID: string
    export const URL_USER: string
    export const URL_TARGETS: string
    export const URL_CATEGORIES: string
    export const URL_WORKOUTS: string
    export const URL_FORGOT_PASSWORD: string
    export const URL_VERIFY_OTP: string
    export const URL_RESET_PASSWORD: string
    export const URL_RESEND_OTP_FORGOT_PASSWORD: string
    export const URL_ACTIVITY: string
}
