export { default as authApi } from './auth.rest'
export { default as categoriesApi } from './categories.rest'
export { default as targetApi } from './target.rest'
export { default as userApi } from './user.rest'
export { default as workoutApi } from './workout.rest'
export { default as workoutHistoryApi } from './workoutHistory.rest'
export { default as activityApi } from './activity.rest'
export { default as notificationApi } from './notification.rest'
